#+TITLE: UwUnyaa's dotifiles

This repository contains some of my dotfiles. Certain ones make no sense to be
contained within this repo, for example suckless software.

The following scripts handle setting up symlinks outside of the repository.
They're intended for use with GNU bash and GNU stow.

Config files are located within the =home= directory of the repo, which is
matching where they will be symlinked to, including their subdirectories.

* These tools have dotfiles in this repo:
- =startx= (=~/.xinitrc=)
- =dunst=
- =foot=
- =kvantum=
- GNU =bash=
- GNU =readline=
- =GIMP=
- =lxterminal=
- =pcmanfm=
- =zeal=
- =htop=
- =river=
- =rivercarro=

* Dependencies:
Make sure you have the following working to get the full experience:
- =river=
- =rivercarro=
- =grim=
- =slurp=
- =wl-clipboard=
- =xdg-desktop-portal-wlr=
- =wlr-randr=
- GNOME polkit agent

In case you're using the X11 screenshot scripts:
- =scrot=
- =maim=
- =slop=
- =xclip=

Also, make sure your sudorders is set up to not prompt for a password, some of
my setup depends on it, and might need adjuestments otherwise.

* Installing:
Just run
#+begin_src sh
  ./install
#+end_src

The script is written in GNU bash and depends on GNU stow to run. In case
you're on arch, the package's names are simply =bash= and =stow=. Both are GNU
software, so they should be to install or even build from source on just about
anything.

* etc dotfiles
There's also some files in the =etc= directory, which are likely to be machine
specific. I'm intentionally not providing a way to install them, as they
should likely be copied over as necessary and potentially modified.

These pieces of software have dotfiles in etc:
- =X11=
- =tlp=
- =inputrc= (default arch file, might be usable somewhere)
- =keyd=

